apiVersion: v1
kind: Secret
metadata:
    name: tea-basic-auth
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Lp9X0Frc2fDKtdn5NvOBA23vKucL0vp2B0LxzsqemNdfUg/BY0X1hsVJEcMN+KklwpEcCy0gxAsCSQ==,iv:jK7O3t+vwiJktoFAFEz/CPEvfUX/izAiioPXjRgzcNM=,tag:hYOb4lXefPMbJh0PeMTCbg==,type:comment]
    #ENC[AES256_GCM,data:fxNr2Rftbjxsqay4DvD/zGgMHX+ySRxhhPs=,iv:IZSE8ivOklXWi9eUwUmW+4JIgT73a84fUq10i4KuCSw=,tag:kR+VsMFzes8n3fq52s4LGw==,type:comment]
    #ENC[AES256_GCM,data:3K5x+ADJafSm3CLCEMAiuQ0fsJnEcNklVq5u8rZZBgFf1nFCkg==,iv:ad0Z8F73fWNfGKr4mkgb1jkPnZDDQw1b4CwH+9QKz/M=,tag:Q6ZZ5AZ1ujBsFK5OsyyfxQ==,type:comment]
    #ENC[AES256_GCM,data:IjZwgSxEKL68s7OcoK9AZSAP1xHFQ4LTW9GxwtcehI8ZQaVNpUVL+rE=,iv:W+bcZOSXjxLCnDdoiGx1Au/wn7IEulWd7nadtGvkYkw=,tag:U4KAvQk9EjAg1Uv5p9ZBug==,type:comment]
    #ENC[AES256_GCM,data:YYpEAqYjIzOzZhLFBUjtsbr9n/ze4u5NeSqUjUkNlmNnbUUG37LaPSmBOH5/1FGEBB1/czeH50DHI8zZLRji,iv:UwufaI13YtDwgPyvKQlvaKanl171HDCwx64n7DjyFA0=,tag:+Z53HwnOV9gQ9xnDAZBcgQ==,type:comment]
    users: ENC[AES256_GCM,data:OSUmzszUtJllAX9XZQCyem+83GMCutI+JYiPMB99IovxVUxI3VeIzm70KR35nV8XnWdSbLxZUejT5ubWjbyp/HwNdw==,iv:ExuJFG/Ig41bK0Ta3NchfIkLokzkV5BLuYV8k1cEi6M=,tag:/vcO75PFCoE2nEXM/Nh5Wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQzk3VSs0WGFCSXNJQmdO
            NW5NblpkN1pDMDV2M2hudFMxR04rTFk3bHlzCmhRQnZZZGpzUStlME01Rm5jbUVj
            U0FEQkwvWmNHVWpLb0VqajNGWmE3ODAKLS0tIFY0L3haWkJBUDFzWE1vakV3NmtE
            bEZNVmMyREJUL3ZTUTNTb092NnVpbDQK6iTlCGYO8W0tWRmw3eY/pHeEDByZO44V
            PaS4BJRb6bR9JC21EPkhqKhp2u0H6Jy8gPjgsV0FdG4DhqmWEXQThw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r8ph8yhw6ulpntwa34jn9k9xj6jdkw96afrtuh5wr3pt8cj0d4vq4e286m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T18:53:20Z"
    mac: ENC[AES256_GCM,data:OBZWgV8+85OdWGB1MIn2w3Wus0+R9AFkcUh9xmZhjS6KWGKJIUA/WZ4Ma8Kv4xHY8aWn+zkrpA3Y76xGyF4vdCZBQIp5Bb/FljVuHUcVdpi1aIWDQXTMVY0f3slO1B9aHAQqCyNeGLOiCCmGlp7sXl6UJUg7E7V2JIm7n0NV7qs=,iv:VQTOehWTFvrDUfQruddmkD9nMGGc2nwGZjU4YPHUo/g=,tag:kJTZkwFNoCIko6iNLBtC6Q==,type:str]
    version: 3.13.3
