apiVersion: v1
kind: Secret
metadata:
    name: tea-secrets
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:2MZ0et9tOpDIzAp61urBZP+xi7DX6erAIFgJDOJAD1EjbcUcz5ATaOV0hUij6xw7G4NnONb1wumMXV8VhRdgn3k//t+wjb7rkTVTu3pxDm2Pu4PFVuCcTsWG3xk8v4aA4YAmTOsxGGUBbIck,iv:RWOO8W3tHZY+XlYRjjL3yjONrwHhItzR3UMk1IA9J4A=,tag:zk9+d2IizEJgPREemf2SZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbW5MQTRTRDZkTmlrY0Zw
            b2F4VDZzWDVpR2hnN0p2VWxEQ1FLdXRXWFZFClJDQkVqQmd3UDNuYmJzZkxUZDRM
            N0Jjc2JuSlR4VjIxaW0ycllDM1FXUWcKLS0tIFRpNEJmNmJZWFlBL29BZk9oQ1B1
            eE5HYXZUSHJoVmNaK0tRZzlZVDlSSDAKUyN0cfkDGQ4mQkNpMmUuxxrPpwjjqsFM
            oSdlLnbmk/wzqeWDTFl7WBM8ev7DHCkqYY6YvgKnGbQzPDbZPmKK3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r8ph8yhw6ulpntwa34jn9k9xj6jdkw96afrtuh5wr3pt8cj0d4vq4e286m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T17:32:14Z"
    mac: ENC[AES256_GCM,data:eiJzdSvWJc2nZq7XJ9EKkg4SDqN1Enq2c9X4l0v0TBcJuwRyvgSXm5rg3yI6ucrZ/ZZsJR4QtL0WhyG1i/jH/taALY34pSZEZLU7YVlWr5SvqvTyzNEHj6B2Rb0nKT483ZQbimWKUzV0Xdc1sftmjGg3pdGsq945cY3sJUlJDi0=,iv:1cX+SPOqGcba+bSwizkJebstYpk72mx7yp5Xk0z6MuI=,tag:baIcpkPB0RM3VfEtbJWUoA==,type:str]
    version: 3.13.3
